[versions]
androidxEspressoCore = "3.6.1"
androidxJunit = "1.2.1"
browser = "1.8.0"
coreKtx = "1.15.0"
material = "1.12.0"
material3 = "1.3.1"
coreSplashScreen = "1.0.1"
jna = "5.16.0"
junitVersion = "4.13.2"
kotlin = "2.1.10"
kotlinxCoroutines = "1.10.1"
rustAndroid = "0.9.6"
appcompat = "1.7.0"
coordinatorLayout = "1.2.0"
googleServices = "4.4.2"
androidGradlePlugin = "8.8.0"
apollo = "4.1.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorLayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashScreen" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines"}

google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime", version.ref = "apollo" }
apollo-api = { module = "com.apollographql.apollo:apollo-api", version.ref = "apollo" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
rust-android = { id = "org.mozilla.rust-android-gradle.rust-android", version.ref = "rustAndroid" }
apollo-android = { id = "com.apollographql.apollo", version.ref = "apollo" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
