[package]
edition = "2021"
name    = "affine_native"
version = "0.0.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
affine_common    = { workspace = true }
affine_nbstore   = { path = "./nbstore" }
affine_sqlite_v1 = { path = "./sqlite_v1" }
napi             = { workspace = true }
napi-derive      = { workspace = true }
once_cell        = { workspace = true }
sqlx             = { workspace = true, default-features = false, features = ["chrono", "macros", "migrate", "runtime-tokio", "sqlite", "tls-rustls"] }
tokio            = { workspace = true, features = ["full"] }

[build-dependencies]
napi-build = { workspace = true }
sqlx       = { workspace = true, default-features = false, features = ["chrono", "json", "macros", "migrate", "runtime-tokio", "sqlite", "tls-rustls"] }
tokio      = { workspace = true, features = ["full"] }
