apiVersion: v2
name: doc
description: AFFiNE doc server
type: application
version: 0.0.0
appVersion: "0.20.0"
dependencies:
  - name: gcloud-sql-proxy
    version: 0.0.0
    repository: "file://../gcloud-sql-proxy"
    condition: .global.database.gcloud.enabled
